### ISSUE TITLE
Add formSubmissionId to Orders and use it as the primary key

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-stock#19]
However

1. The `id` field will be retained
1. The `id` field will allow for nulls before it is synced to the server & the client receives the CouchDB `id`
1. The `id` field will be unique

Tasks:

- [x] Add formSubmissionId field which will be the primary key to the Repository & Order class
- [x] Change the `id` field to follow the rules above
- [x] Add it to the Repository class property-extraction-from-cursor methods, ContentValue creator method
- [x] Add the `formSubmissionId` field to the Order sync class -> JSON deserialization method

**Comment by craigappl** [comment]
Reviewed and Closing this issue
