### ISSUE TITLE
Implement Individual Stock adjustment form

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-stock#49]
Implement Individual Stock adjustment form

![individual adjust 1](https://user-images.githubusercontent.com/25123762/44993982-419be300-afa5-11e8-8c12-d3d5bffac708.png)

- [x] The step should be defined in a json config
- [x] The toolbar should have the title loss/adjustment and the Trade item name
- [x] The toolbar should have an 'x' icon that when clicked returns to the stock on hand view
- [x] The bottom navigation should have a save button that by default is disabled.
- [x] The lot widget is shown on opening form with no selection 
- [x] Selecting a lot enables the other data entry widgets as shown on the below screen shot

![individual adjust 2](https://user-images.githubusercontent.com/25123762/44994123-dc94bd00-afa5-11e8-8564-3fe16bdbca2d.png)

- [x] The lot widget has Stock on Hand, Physical count and Status Input fields and the  plus(+) and subtract(-) icons
- [x] The clicking on  plus(+) and subtract(-) icons  adds or subtracts the physical count 
- [x] The physical count can be updated/typed into
- [x] Lot codes and Status are dropdowns
- [x] Stock on hand is a read-only field
- [x] The lot widget has an add lot button
- [x] Clicking the add lot button adds a row to the lot component, such that one can select lot, input changes and select status
- [x] The Lot row added by add lot button has a cancel button which removes the entire row.
- [x] The widget is able to validate stock issue so that stock balance is never negative
- [x] Adding a new lot row disables the Save button till all inputs in the row are valid or row is removed
- [x] One is not able to add the same lot twice
- [x] Lots drop-down should be ordered by expiry date
- [x] In Lots drop-down lots with expiry date less than 3 months time should be displayed in red

![individual adjust 3](https://user-images.githubusercontent.com/25123762/44994355-ed91fe00-afa6-11e8-9738-f1a71a767c90.png)

- [x] Whenever the widget is in a valid state the Save button is activated
- [x] Saving opens the stock details screen and refreshes the stock transactions
- [x] The bottom navigation bar displays the number of lots adjusted

**Comment by vincent-karuri** [comment]
<img width="465" alt="screen shot 2018-09-10 at 15 47 11" src="https://user-images.githubusercontent.com/33488286/45298338-e3c14b00-b510-11e8-90c4-4cc87813d87c.png">

Not sure if this is an issue but there are duplicate lot code numbers and the ordering of the lots is not by expiry date

**Comment by vincent-karuri** [comment]
<img width="465" alt="screen shot 2018-09-10 at 15 56 03" src="https://user-images.githubusercontent.com/33488286/45298762-30595600-b512-11e8-9bf6-adbf12435d03.png">

This has a similar issue with duplicate reason strings

**Comment by vincent-karuri** [comment]
<img width="469" alt="screen shot 2018-09-10 at 16 00 23" src="https://user-images.githubusercontent.com/33488286/45299033-f63c8400-b512-11e8-94f7-297a94ea83e9.png">

It shows that 6 vials are available but are not reflected in the lots summary section.

These are the 6 vials I added, there were 0 vials before the stock take.

**Comment by vincent-karuri** [comment]
<img width="468" alt="screen shot 2018-09-10 at 16 04 10" src="https://user-images.githubusercontent.com/33488286/45299116-3b60b600-b513-11e8-8f89-f34fed8c43a9.png">

If you go back to the landing page and navigate back to the stock summary page of the recently updated stock, the changes seem to have disappeared.

**Comment by vincent-karuri** [comment]
<img width="472" alt="screen shot 2018-09-10 at 16 08 27" src="https://user-images.githubusercontent.com/33488286/45299291-cfcb1880-b513-11e8-985a-157dc6f73e06.png">

Lot count is off.

**Comment by vincent-karuri** [comment]
<img width="468" alt="screen shot 2018-09-10 at 16 13 02" src="https://user-images.githubusercontent.com/33488286/45299486-71eb0080-b514-11e8-8093-927a0387f29b.png">

<img width="462" alt="screen shot 2018-09-10 at 16 13 32" src="https://user-images.githubusercontent.com/33488286/45299498-7adbd200-b514-11e8-83e2-1fb7a3aa1e29.png">

Again, not sure if this is an issue but BCG and Measles commodity types appear twice.

**Comment by vincent-karuri** [comment]
Please add stock so as to easily verify that stock on hand is being displayed. Currently, all trade items have 0 doses/vials.
