### ISSUE TITLE
Issues that came up in September

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-stock#58]
This is a list of issues that have come up in September that were different from the original scope:

- We made the assumption that all Orderables have a commodityType and Trade Item. If they don't have those, we are not going to include them.
- We made the assumption that all trade items have a commodityType. The OpenLMIS demo data has trade items that are not associated with commodityTypes. We decided to filter out these items and only show orderables that have a tradeItem ID grouped by commodityType. If trade items can't be linked to a commodityType, we should create a generic commodityType "Other" and use that as the grouping mechanism.
- VVM is a field that is collected on some orderables only.
- Lots are actually orderable dependent. Some orderables track lots, not others. The idea of a global lot trigger is not valid.
- We need to sync the list of facilities that are populated in the "Received From" and "Issued To" fields in the multi-step transaction forms. This is based on the supply chain hierarchy and is different per facility.

**Comment by vincent-karuri** [comment]
Why does this  trade item: `4e59b2cb-c9fb-4103-9ac7-f087cec868c5`, appear under so many different commodity types?

**Comment by vincent-karuri** [comment]
Commodity type `bb66a9c4-8443-42ee-b701-caf00061f4df` appears under two orderables but with different orderable names, should this happen?
