### ISSUE TITLE
Create Shipment model & it's related persistence classes

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-stock#6]
- [x] Design the model on the client side
- [x] Create the Shipment, ShipmentLineItem objects class
- [x] Implement the persistence classes
- [ ] Add relevant tests for the persistence classes

![opensrp openlmis integration - client side model](https://user-images.githubusercontent.com/31766075/37089266-0beabe24-2211-11e8-8f19-9c912376fef8.jpg)

More on the data required to be saved [here](https://openlmis.atlassian.net/wiki/spaces/OP/pages/229900293/OpenSRP-OpenLMIS+Proof+of+Concept+Software+Requirement+Specification#OpenSRP-OpenLMISProofofConceptSoftwareRequirementSpecification-AndroidClientUIEnhancements)

**Comment by craigappl** [comment]
Reviewed and Closing this issue
