### ISSUE TITLE
Implement Stock take 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-stock#61]
Implement to stock take Form

- [x] The stock take screen has  a tool bar with a title `Stock take`
- [x] The  stock take screen tool bar has a close `X` icon that when clicked returns to stock on hand screen
- [x] Stock take has a search widget that filters the list being adjusted. One can search by Program, Commodity type or Trade Item

![stocktake 1](https://user-images.githubusercontent.com/25123762/45625794-707e8280-ba96-11e8-8afa-213740a1680c.png)

- [x] The Stock screen has a list of trade items grouped by commodity type just like Stock on hand but each trade item row has a a list of lots stock adjustment form(lot widget)
- [x] The lot widget has `Stock on Hand`, `Physical count` and `Status` Input fields and the plus(+) and subtract(-) icons and `no change` icon
- [x] The clicking on plus(+) and subtract(-) icons adds or subtracts the `physical count`
- [x] The` physical count` can be updated/typed into
- [x] `Status `is a dropdown
- [x] `Stock on hand` is a read-only field
- [x] Clicking the `no change` icon enable the save button
- [x] The lot widget has a `save` button which by default is disabled
- [x] The widget is able to validate stock issue so that stock balance is never negative
- [x] After stock is adjusted by typing into `physical count` text field or clicking the` add/minus buttons` the `different` text field is shown and is populated with the difference, also `reasons` dropdown is shown

- [x] Stock take has a bottom navigation panel
- [x] The bottom navigation panel has an information text field on the left that displays stock adjustments, `Save draft` button and a `Save` button that is disabled until stock take is completed 

![stocktake 2](https://user-images.githubusercontent.com/25123762/45626201-8b9dc200-ba97-11e8-99ca-8c03f1aecde9.png)

- [x] If all the lots within a trade item are in a valid state the `Save` button is enabled
- [x] Clicking on `Save` button marks saves all the lots within the trade item in the draft mode

- [x] All trade items that have completed being adjusted are collapsed(lot adjust form is hidden) and show's a Green ticked icon, name of the trade item and details of adjustment(Total doses changed and difference) and also an edit icon

![stocktake 3](https://user-images.githubusercontent.com/25123762/45626400-28605f80-ba98-11e8-8331-6c3f110aca85.png)

- [x] Clicking on edit icon opens the stock adjustment form
- [x] As save button is clicked the bottom navigation information text field is also updated with number of trade items out of total that stock take has been completed
- [x] Also the bottom navigation information text field also shows the last updated time for the stock take draft
- [x] Clicking on the save as Draft saves the current progress of the stock take and returns to `stock on hand screen`.
- [x] Opening the `stock take screen` after  saving a draft restores the state the form had when saving the draft

![stocktake 4](https://user-images.githubusercontent.com/25123762/45626922-66aa4e80-ba99-11e8-9e69-98e1bfdf7f66.png)

- [x] After stock take is completed for all the trade items the Save button is activated
- [x] Clicking on the submit button Saves the stock take and performs the stock adjustment and opens the stock on hand screen

**Comment by githengi** [comment]
- [ ] Display only commodity types and trade items with lots that have not expired on stock take screen

**Comment by githengi** [comment]
- [ ] Store  an adjustment with value '0' and reason "Physical Inventory" when no change button is clicked. This will later create a stock event when submit is clicked

**Comment by vincent-karuri** [comment]
Press `No Change` button then scroll down until the button is out of view then scroll back up to the button. The blue background disappears on the button.

**Comment by vincent-karuri** [comment]
One can press `No Change` button and still make stock adjustments with the `-` and `+` buttons.

I'm not sure if this should be allowed.

**Comment by vincent-karuri** [comment]
One can still submit/save even when stock is negative.

**Comment by vincent-karuri** [comment]
When doing a stock take then exit to the landing page after saving as draft, I'm not able to save changes on edits.

**Comment by vincent-karuri** [comment]
<img width="473" alt="screen shot 2018-10-01 at 14 40 33" src="https://user-images.githubusercontent.com/33488286/46286500-0b438a80-c588-11e8-9826-96bb1d6ac7f5.png">

Difference is wrongly calculated after saving as draft then coming back to the stock take screen.

It seems to be equal to stock on hand.

**Comment by vincent-karuri** [comment]
Filter only seems to work for a few commodity types and trade items.

**Comment by githengi** [comment]
- [ ] Reset any changes after clicking `No Change` button

- [ ] If  `No Change` button is clicked disable other inputs(+ and - buttons and typing into Physical count)
