### ISSUE TITLE
Implement Stock take in non-lot managed trade items

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-stock#64]
Implement Stock take in non-lot managed deployments

Stock take for non-lot managed deployments is exactly as in issue [https://github.com/OpenSRP/opensrp-client-stock/issues/61](https://github.com/OpenSRP/opensrp-client-stock/issues/61)

- [x] The only difference is that lots codes and expiration are not shown and adjustments are done once per trade item and not in all lots in a trade item

- [x] The below screen shots illustrate the difference

![stocktake 1 1](https://user-images.githubusercontent.com/25123762/45628764-7461d300-ba9d-11e8-923a-7432447711f4.png)

The stock adjustment form when a stock adjustment is done or no change is clicked the below is displayed
![stocktake 2 1](https://user-images.githubusercontent.com/25123762/45628767-79268700-ba9d-11e8-8de8-dfb094d0d8c8.png)

**Comment by craigappl** [comment]
@githengi , just note that this is no longer a requirement. Now that we have switched to the extraData approach where we track whether that trade item captures the lot or not, each trade item may or may not capture lots. If they don't capture lots, we don't need to show lots in that trade item.

**Comment by githengi** [comment]
@craigappl Noted. I have renamed the Issue reflect  `Implement Stock take in non-lot managed trade items`. The Stock take Card will be different depending on whether a trade item has lots or not
