### ISSUE TITLE
Update Sync and filter Logic on Stock on hand View

### ISSUE THREAD

**Issue by vincent-karuri** [OpenSRP/opensrp-client-stock#69]
- [x] Fix crash that happens after sync and during refresh

- [x] Fix Program filter bug that prevents filter by Program

**Comment by githengi** [comment]
- [ ] Refresh programs spinner options during sync
- [ ] Retain Selected Program  after sync refreshes stock on hand
- [ ] Filter trade items without names for program filter or FTS search
- [ ] Populate FTS search repository during sync
