### ISSUE TITLE
Feedback From 4 Oct 2018

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-stock#82]
This document provides feedback on the app that was delivered on 4th Oct

### Login:
- [x] Login Screen, sync and logout were tested for the vnurse1 user and everything works as intended.
### Landing Page:
- [x] Expand All and Collapse All works as intended
- [x] Trade items are displayed correctly (names, number of available and number of doses)
- [ ] The 3 dot option menu next to each commodity type displays a stock planning menu that doesn't link anywhere. Please remove the option menu
![screenshot_1538679638](https://user-images.githubusercontent.com/6067053/46496529-25ba7580-c7cd-11e8-90ca-acf20771d9cc.png)
- [ ] Syringes say the number of doses, but it should be based on the dispensible that's linked in the orderable commodity type routeOfAdministration
![screenshot_1538679724](https://user-images.githubusercontent.com/6067053/46496696-834ec200-c7cd-11e8-9bd0-cfd8be8ffcd4.png)

### Flows for Syringe (tradeItems with hasLots:false, useVvm:false)
- [ ] Opened Acme Syringe 0.05ml
![screenshot_1538679923](https://user-images.githubusercontent.com/6067053/46496803-ca3cb780-c7cd-11e8-972d-74039da126fe.png)
- [ ] The word "doses" should be based on the trade item orderable's dispensible route of Administration
- [ ] Clicked Received
![screenshot_1538680578](https://user-images.githubusercontent.com/6067053/46497415-513e5f80-c7cf-11e8-96d3-d87cae3d5f7b.png)
- [x] The Vials received should not say the word "Vials". We should just hard code this to "Quantity Received"
- [x] Status should not be displayed because useVvm:false in the trade item orderable's record
- [ ] Received from is blank (This may be due to metadata problems that I need to review)
- [x] Clicked submit without entering vials received
![screenshot_1538680783](https://user-images.githubusercontent.com/6067053/46497584-d45fb580-c7cf-11e8-92d6-a2af6afb57a2.png)
- [x] The popup says "vials". We should just change this to "Please specify the quantity received." The blue text "vials received" should just be hardcoded to  "Quantity received"
- [x] Clicked submit and the transaction record does not update
![screenshot_1538681046](https://user-images.githubusercontent.com/6067053/46497795-6b2c7200-c7d0-11e8-8f95-bfb68b68002b.png)
- [x] Clicked back button in top left corner and when back into the Acme syringe0.05ml and the transaction record doesn't show up.
![screenshot_1538681245](https://user-images.githubusercontent.com/6067053/46497952-de35e880-c7d0-11e8-80f9-11bcc9a86ccc.png)
- [ ] Clicked Issued (2 screenshots)
![screenshot_1538681311](https://user-images.githubusercontent.com/6067053/46497994-058cb580-c7d1-11e8-81f2-7e265b8d7064.png)
![screenshot_1538681327](https://user-images.githubusercontent.com/6067053/46498007-0f161d80-c7d1-11e8-8f7c-c9bc946d4279.png)
- [ ] Issued to is blank (This is probably a metadata mapping issue that I will look at)
- [x] Syringes Issued should just be changed to the string "Quantity Issued"
- [x] "2 children vaccinated today. Assuming 300 dose(s) used." Should be removed
- [x] Status should not display because useVvm:false in the trade item orderable
- [x] Wasted Vials should be hard coded "Quantity Wasted"
- [ ] Wasted reason is fine. I have a bigger discussion point here. What happens to the wasted vials and wasted reason when we save the form? I think it should save an adjustment type form. We will want to 
- [x] The Wasted Reasons should be the same as what's in the issue reasons above.
![screenshot_1538682671](https://user-images.githubusercontent.com/6067053/46499266-6d90cb00-c7d4-11e8-9c36-13a35bc1c8c5.png)
- [x] I couldn't save the form, but there were no errors produced. This is likely because the issued to field isn't available. I assume the "Syringes Issued" portion should be a required field like the Quantity Received field is in the Received form.
- [x] Clicked back to the stock card screen and clicked the Loss/Adjust button
- [x] Clicked the plus button 3 times and the reason did not populate
![screenshot_1538682972](https://user-images.githubusercontent.com/6067053/46499417-e2fc9b80-c7d4-11e8-93be-a90692468241.png)
- [x] Clicked the minus sign button until the value was negative and the error popped up. This is working correctly.
- [x] Clicked the back button
- [x] Returned to the landing page

### Flows for BCG (tradeItems with hasLots:true, useVvm:true)
- [ ] Clicked on Intervax BCG Dilutent (20 dose)
![screenshot_1538683820](https://user-images.githubusercontent.com/6067053/46500123-dc6f2380-c7d6-11e8-809d-935f3675f4f1.png)
- [x] The layout and buttons on this screen are displaying correctly.
- [ ] The To/From Damaged, transfer In rows which are losses and adjustments seem a little weird. There is something called "Damaged" but it adds a value of 1 to the ledger. It should be a negative number, I think.
- [ ] Clicked the Received Button
![screenshot_1538684090](https://user-images.githubusercontent.com/6067053/46500350-7df67500-c7d7-11e8-8a0a-d46e7bf204e7.png)
- [ ] The Receive from doesn't populate, but that may be a metadata issue.
- [x] Couldn't click next because the receive from button wasn't activated.
- [x] Clicked the back button to return to the stock card view
- [x] Clicked the Issued Button
![screenshot_1538684655](https://user-images.githubusercontent.com/6067053/46500883-ce220700-c7d8-11e8-85b7-21d8b3bf63a5.png)
- [x] Couldn't click next because the Issued to section isn't filled.
- [x] Clicked the back button to return to the stock card view
- [x] Clicked Loss/Adj
![screenshot_1538684701](https://user-images.githubusercontent.com/6067053/46500943-ea25a880-c7d8-11e8-9680-bd8968727468.png)
- [x] The screen doesn't display anything, but the add lot button works
- [x] Clicked back twice to return to the landing page

### Stocktake review
- [ ] Clicked the plus button and Stocktake from the landing page
![screenshot_1538684785](https://user-images.githubusercontent.com/6067053/46501011-1a6d4700-c7d9-11e8-8eb2-d2e57ca65d2b.png)
- [x] Search box works
- [x] Displays all commodityType categories correctly. (8 total)
- [x] 5 items are able to be adjusted because 3 are non-lot trade items. Therefore, the calculation in the bottom is correct.
- [x] The reasons in the dropdown should be the same as the adjustment reasons
![screenshot_1538685043](https://user-images.githubusercontent.com/6067053/46501243-c3b43d00-c7d9-11e8-9f51-fd693eec28c7.png)
- [x] Saved a change and clicked save as draft
- [x] Returned me to the landing page. I clicked the plus sign and stocktake. I returned to the form and it saved correctly exactly as I had it.
- [x] I completed all items 
![screenshot_1538685261](https://user-images.githubusercontent.com/6067053/46501394-36bdb380-c7da-11e8-88fd-b2246635bb9c.png)
- [ ] I clicked submit
- [ ] I entered Intervax BCG to verify. It displays the physical inventory as intended for no change. I could not check trade item orderables with hasLots:false

Server Analysis (Did each stock event push as required?)
- [x] Opened https://vreach-dev.smartregister.org/opensrp/rest/stockresource/sync?serverVersion=0
- [x] There are 25 items returned, but none of them were from today October 4th, so it suggests there's a sync issue. Also, the background data doesn't seem to have the orderableId as a separate field.

**Comment by githengi** [comment]
> Syringes say the number of doses, but it should be based on the dispensible that's linked in the orderable commodity type routeOfAdministration

@craigappl How will this be aggregated if the trade items orderables have a different dispensable

**Comment by craigappl** [comment]
@githengi We have to assume that the commodityType and trade item dispensible are the same.
